name: Build FullStack

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      # --- Build Docker image ---
      - name: Build Docker image
        run: docker-compose -f docker-compose.yml up --build -d

      # --- Run Playwright tests directly in runner ---
      - name: Run Playwright tests
        working-directory: ./endToEndTests
        run: |
          npx playwright test
