name: Build FullStack

on:
  pull_request:
    branches:
      - main

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: API
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

  playwright-tests:
    runs-on: ubuntu-latest
    needs: [build-api, build-client]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install Playwright
        run: |
          cd endToEndTests
          npm ci
          npx playwright install chromium

      - name: Start API (prod)
        working-directory: ./API
        run: DOTNET_HOSTING_URLS=http://127.0.0.1:5000 dotnet run --no-build &

      - name: Serve Client (prod build)
        run: |
          npm install -g serve
          serve -s ../client/build -l 3000 &

      - name: Wait for services
        run: npx wait-on http://127.0.0.1:5000 http://localhost:3000

      - name: Run Playwright tests
        run: |
          cd endToEndTests
          npx playwright test --reporter=github --reporter=html

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: endToEndTests/playwright-report
          retention-days: 7
