name: Build FullStack

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      # --- Start services using docker compose ---
      - name: Start services
        run: |
          docker compose build
          docker compose up -d

          echo "Waiting for application to start..."
          npm install -g wait-on
          if ! wait-on --timeout 60000 http://localhost:8080; then
            echo "Application failed to start. Checking logs..."
            docker compose logs
            exit 1
          fi

          echo "Application is up. Checking logs before running tests..."
          docker compose logs

          echo "Testing API health..."
          curl -v http://localhost:8080/api/health || true

          # Install and run tests
          cd endToEndTests
          npm ci 
          npx playwright install --with-deps

          # Run tests with increased timeout
          PLAYWRIGHT_TEST_TIMEOUT=30000 npx playwright test --reporter=github --reporter=html
