name: Build FullStack

on:
  pull_request:
    branches:
      - main

jobs:
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t fullstack-app .

  playwright-tests:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Playwright
        run: |
          cd endToEndTests
          npm ci
          npx playwright install chromium
          npm install -g wait-on

      - name: Run Docker container
        run: |
          docker run -d --name fullstack-app -p 5000:5000 fullstack-app
          # Wait for API (and React is served through API)
          if ! wait-on --timeout 30000 http://localhost:5000; then
            echo "ERROR: App did not start successfully"
            docker logs fullstack-app
            exit 1
          fi
          echo "App is ready!"

      - name: Run Playwright tests
        run: |
          cd endToEndTests
          npx playwright test --reporter=github --reporter=html

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: endToEndTests/playwright-report
          retention-days: 7

      - name: Stop Docker container
        run: docker stop fullstack-app
