name: Build FullStack

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      # --- Build Docker image ---
      - name: Build Docker image
        run: docker build -t fullstack-app .

      # --- Run fullstack app container ---
      - name: Run fullstack app container and test
        run: |
          docker run -d \
            --name fullstack-app \
            -p 8080:8080 \
            fullstack-app

          # Wait for API + client to be ready
          npm install -g wait-on
          if ! wait-on --timeout 30000 http://localhost:8080; then
            docker logs fullstack-app
            exit 1
          npm ci
          npx playwright install
          npx playwright test --reporter=github --reporter=html --project=chromium
          fi
