name: Build FullStack

on:
  pull_request:
    branches:
      - main

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: API
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

  playwright-tests:
    runs-on: ubuntu-latest
    needs: [build-api, build-client]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install Playwright
        run: |
          cd endToEndTests
          npm ci
          npx playwright install


      - name: Install test helper
        run: npm install -g start-server-and-test

      - name: Run Playwright tests (API + Client)
        run: |
          cd endToEndTests
          npx start-server-and-test \
            "dotnet run --project ../API --urls http://localhost:5000" http://localhost:5000 \
            "serve -s ../client/build -l 3000" http://localhost:3000 \
            "npx playwright test --reporter=github --reporter=html"
